spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # schema generation with hibernate
  sql:
    init:
      platform: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql